server:
  port: 6450
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/results?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      jwt-key: MjWP5L7CiDff90qA
      client:
        client-id: results-service
        client-secret: 309_res9ults_86
        authorization-grant-type: client_credentials
        scope: read
        access-token-uri: http://localhost:9000/oauth/token
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always
