server:
  port: 9000
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  jpa:
    database: MYSQL
    generate-ddl: false
database:
  clinic-employee-database:
    platform: mysql
    url: jdbc:mysql://mysql/clinic?createDatabaseIfNotExist=true
    username: root
    password: clinic33789
    driverClassName: com.mysql.cj.jdbc.Driver
  clinic-client-database:
    platform: mysql
    url: jdbc:mysql://mysql/client?createDatabaseIfNotExist=true
    username: root
    password: clinic33789
    driverClassName: com.mysql.cj.jdbc.Driver
oauth:
  jwt-key: MjWP5L7CiDff90qA
  clients:
    - name: web-frontend
      password: 11front_45_jt590
      grantTypes:
        - password
      scopes:
        - read
        - write
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 43200

    - name: registration-service
      password: reg_554_service14
      grantTypes:
        - client_credentials
      authorities:
        - INTERNAL
      scopes:
        - read
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 43200

    - name: results-service
      password: 309_res9ults_86
      grantTypes:
        - client_credentials
      authorities:
        - INTERNAL
      scopes:
        - read
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 43200
