server:
  port: 9000
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
database:
  clinic-employee-database:
    platform: mysql
    url: jdbc:mysql://mysql/clinic?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  clinic-client-database:
    platform: mysql
    url: jdbc:mysql://mysql/client?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
oauth:
  jwt-key: MjWP5L7CiDff90qA
  clients:
    -
      name: registration-service
      password: reg_554_service14
      grantTypes:
        - password
        - refresh_token
      scopes:
        - read
        - write
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 43200
    -
      name: results-service
      password: 1789results_11service6
      grantTypes:
        - password
        - refresh_token
      scopes:
        - read
        - write
      accessTokenValiditySeconds: 1800
      refreshTokenValiditySeconds: 43200
