server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://discovery-server:8761/eureka
spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090/admin
  application:
    name: DISCOVERY-SERVER
  security:
    oauth2:
      jwt-key: MjWP5L7CiDff90qA
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always