server:
  port: 32768
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql/client?createDatabaseIfNotExist=true
    username: root
    password: clinic33789
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      jwt-key: MjWP5L7CiDff90qA
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      show-details: always
