server:
  port: 6340
eureka:
  instance:
    prefIpAdress: true;
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql/registration?createDatabaseIfNotExist=true
    username: root
    password: clinic33789
    driverClassName: com.mysql.cj.jdbc.Driver
